filter_path = "resources/filter_de.txt"
generate_abbrv = false
generate_skip_grams = false

[corpora]
[corpora.example]
path = "resources/example_gbif.tsv"
generate_abbrv = true
generate_skip_grams = true
skip_gram_min_length = 2
skip_gram_max_skips = 2

[corpora.compressed]
path = "resources/example.csv.gz"
generate_abbrv = true
generate_skip_grams = true
[corpora.compressed.format]
delimiter = ";"
